public class Constans {
    public static final String ERROR_MIN_AGE = 'Insufficient minimum age';
    public static final String ERROR_FLIGHT_STATUS = 'The flight has already departed';
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String FLIGHT_STATUS_PAST = 'Past';
    public static final String FLIGHT_STATUS_OFFER_PENDING = 'Offer Pending';
    public static final String FLIGHT_STATUS_REQUSTED = 'Requested';
    public static final Integer FLIGHT_DELETION_PERIOD_DAYS = 30;
    public static final String THE_NAME_MUST_BE_NOT_EMPRY = 'The name must be not empty.';
    public static final String THE_AGE_MUST_BE_A_NUMBER = 'The age must be a number.';
    public static final String KEY_WEATHERBIT = 'd0c8611639e547788e6b0a2910e13a27';
    public static final String ERROR_RECEIVING_REQUEST = 'Error receiving request';
    public static final String REQUEST_METHOD_GET = 'GET';
    public static final String REQUEST_PARAMETR_AGE = 'age';    
    public static final String REQUEST_PARAMETR_FUZZYNAME = 'fuzzyname';
    public static final Integer STATUS_CODE_200 = 200;
    public static final Integer STATUS_CODE_404 = 404;
    public static final Integer STATUS_CODE_409 = 409;
    public static final String RESPONSE_DATA_DATA = 'data';
    public static final String RESPONSE_DATA_DATETIME = 'datetime';
    public static final String RESPONSE_DATA_TEMP = 'temp';
    public static final String GENERAL_ERROR = System.Label.General_Error;
}